### ISSUE TITLE
Feature suggestion: open link in new window

### ISSUE THREAD

**Issue by Trevoke** [dailydrip/firestorm#52]
Clicking on a link, right now, leaves the forum to go to whatever the link is. Maybe we want to keep the forum page open and just open a new browser window?

**Comment by agustif** [comment]
Some CMS implement an intersitial with a notice -You're leaving the Forums- and the link with the url to the outside world link

**Comment by j127** [comment]
I think that it's generally better for usability to open links in the same tab. That way, users can choose how they want to open links:

* **Same tab:** left click
* **New tab:** ctrl-click (or middle click)
* **New window:** shift-click

Using `target="_blank"` removes those choices from the users and makes the behavior unpredictable, because even savvy users can't always see whether a link is internal or external before clicking.

There is a good write-up here: https://css-tricks.com/use-target_blank/

**Comment by Trevoke** [comment]
Hmm... Fair enough.

**Comment by agustif** [comment]
We should maybe treat differently external urls, not doing so may be a hint for spammers that they efforts will be recompensated with views. I dont know, I just would advise on doing something on external links, but maybe it's not needed.

**Comment by OvermindDL1** [comment]
> We should maybe treat differently external urls, not doing so may be a hint for spammers that they efforts will be recompensated with views. I dont know, I just would advise on doing something on external links, but maybe it's not needed.

What Discourse does by default is mark any external links by any people in the newbie groups as rel="no-follow" or so, and only removes that once they are higher in rank, this is really the best thing to do.

**Comment by j127** [comment]
On my own forums, I put `rel=nofollow` on all external links and then have a whitelist for certain external domains (just a textarea on the settings page with one line per domain pattern).

I wouldn't remove nofollow on my own sites, because there are a couple of types of spammers that would take advantage of it. I think that users should be motivated by sharing knowledge rather than by link juice. It leads to better conversations. I also disable user signatures for similar reasons.

**Comment by agustif** [comment]
User signatures are a nightmare in most forums, having mods to enforce rules or disable all tags like img and such...

**Comment by Trevoke** [comment]
Let's stick to the topic of "opening links"; if we want to discuss user signatures, let's start a new thread.
