### ISSUE TITLE
Cannot fill tag entry

### ISSUE THREAD

**Issue by elpikel** [dailydrip/firestorm#64]
When i click on tag input it hides so i can't fill any text. Also it is possible to send empty tag. Can I take care of this ?

**Comment by knewter** [comment]
Sorry I didn't ever respond to this issue. I should really turn notifications back on - I just used to get so many that it ate my soul. Anyway, I haven't re-added tags since the 1.3 rewrite. I'm going to close this issue and hopefully when I add them again I'll actually implement a decent ux for it :) Alternatively, if you want to add tags I'm always glad to work with anyone to help them contribute.
