### ISSUE TITLE
Clicking on "Sign In" does not reflect signed in state

### ISSUE THREAD

**Issue by peteygao** [dailydrip/firestorm#81]
1) First on the homepage:
![click me](https://user-images.githubusercontent.com/2184561/27107713-6bd4471e-504e-11e7-81dd-6fb4fbd3617b.png)
2) Then on the logged in page, the bottom-left button still says "Log In":
![wut](https://user-images.githubusercontent.com/2184561/27107722-78fb5fae-504e-11e7-8efb-06dc674a2c44.png)

Clicking on "Log In" _again_ will finally result in the correct state being displayed (namely, the link text changes to "Log Out").

I'm relatively new to Elixir and Elm, but I'm happy to help out and attempt to fix this "bug" if someone with more experience on the project can point me in the right direction in terms of where the logic for this stuff lives 😄!

**Comment by knewter** [comment]
Sorry, this is covered in a few other issues, but this is because we don't support signing in with anything but GitHub presently. I'm *almost* caught up to the current state in my rebuild of the project from scratch in Phoenix 1.3 in episodes on https://www.dailydrip.com/topics/elixir - once that's done that branch will take over as `master` and I'll start adding functionality like signing in with other oauth providers (first) and creating your own account (after that) without an oauth provider.

The goal is still to shoot for a July 4th 1.0 release with the items mentioned in the milestones complete. I'm expecting to get the next couple of days free to work on it more-than-full-time as the family's going out of town and I'm pushing desperately to get it done by my self-imposed release date :)

**Comment by knewter** [comment]
(closed the issue since it's a known thing and it's covered in the existing issues)
